**NumPy - numeric Python**

In [4]:
nums = [1,2,3,4,5]
sq = []

for i in nums:
  sq.append(i*i)

print(sq)


[1, 4, 9, 16, 25]


In [5]:
nums = [1,2,3,4,5,6,7,8,9]

sq = [x*x for x in nums]  # using comprehension
print(sq)


[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# numpy array  [1 2 3 4 5 6 7 8 9] 1D
# DIff in list and numpy is 'comma'  in numpy no comma , seperated by space

[1 2 3 4 5 6 7 8 9]


In [10]:
sq = arr**2
print(sq)

[ 1  4  9 16 25 36 49 64 81]


**Creating Numpy array from 1D list**

In [14]:
lst=[9,26,13,1,45,30,12,10,89,31]

arr = np.array(lst)

print(lst)
print(type(lst))


print(arr)
print(type(arr))

[9, 26, 13, 1, 45, 30, 12, 10, 89, 31]
<class 'list'>
[ 9 26 13  1 45 30 12 10 89 31]
<class 'numpy.ndarray'>


**Creating Numpy array from 2D list**

In [15]:
lst = [
    [5,2,1,3],
    [4,7,8,9],
    [1,5,3,8]
]

print(lst)

[[5, 2, 1, 3], [4, 7, 8, 9], [1, 5, 3, 8]]


In [16]:
arr = np.array(lst)
print(arr)   # 2D numpy

[[5 2 1 3]
 [4 7 8 9]
 [1 5 3 8]]


**Creating numpy array with 0's and 1's**

In [27]:
x = np.zeros(3)
print(x)   # 1D

print()

z = np.zeros((3,4))
print(z)   # 2D


[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
on = np.ones(4)
print(on)

print()
o = np.ones((4,5))
print(o)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# we want to fill the another element use -> full((row,col),ele)
arr = np.full((3,3),5)
print(arr)

print("\n")

arr1 = np.full((4,3),8)
print(arr1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


**creating Identity Matrix**

In [24]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**create numpy array using arange()**

In [29]:
# creates a numbers within a range.
arr = np.arange(1,6)
print(arr)


[1 2 3 4 5]


In [36]:
# np.arange(start, stop, step)
arr = np.arange(2,11,2)
print(arr)

[ 2  4  6  8 10]


In [37]:
arr = np.arange(50,25,-3)
print(arr)

[50 47 44 41 38 35 32 29 26]


**create numpy array using arange()**

np.linspace() creates numbers with equal gaps between a start and end value.

In [41]:
arr = np.linspace(1,10,2)
print(arr)

[ 1. 10.]


In [42]:
arr = np.linspace(1,13,9)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]


**Multiple Types**

In [45]:
lst = ['joe', 9.86, 45, True]

for i in lst:
  print(type(i))

<class 'str'>
<class 'float'>
<class 'int'>
<class 'bool'>


In [47]:
arr = np.array(lst)   # numpy stores the homogeneous data types only one type of data store
print(arr)            # it convert all into string

for i in arr:
  print(type(i))


['joe' '9.86' '45' 'True']
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
