Day 2 - Indexing, Slicing & Reshaping

1. Array indexing

2. Negative indexing
3. 2D indexing
4. Array slicing
5. 2D slicing
6. Changing elements
7. reshape()
8. flatten()
9. ravel()
10. Array iteration

**What is Array Indexing?**

**Indexing means accessing an element from an array using its position.**

In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40])  # numpy arr index start from 0
print(arr[0])

10


**what is the Negative Index ?**

**Negative indexing is used to access array elements from the end using negative index values.**

In [5]:
print(arr[-1])  # last element 40
print(arr[-2])  # second last element 30


40
30


**2D Indexing**

**for 2D array we use two indexes arr[row, col]**

In [9]:
# 2D array indexing is used to access an element using its row and column index.
arr2d = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr2d)
print(arr2d[1,1])  # print 50
print(arr2d[0,0])  # print 10


[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
10


**Array Slicing**

arr[start : stop : step]

**Array slicing extracts a portion of an array using indexes.**

1. : - all / range
2. start: - start to end
3. :stop - beginning to stop
4. ::step - skip elements
5. [::-1] - reverse the array

In [24]:
arr1 = np.array([90,60,80,30,20])

print(arr1[1:4])   # end not include
print(arr1[2:])
print(arr1[:3])
print(arr1[:])   # print arr

print(arr1[::2])  # start stop step
print(arr1[1::2])

print(arr1[::-1])  # reverse arr
print(arr1[3:0:-1]) # reverse from index 3


[60 80 30]
[80 30 20]
[90 60 80]
[90 60 80 30 20]
[90 80 20]
[60 30]
[20 30 80 60 90]
[30 80 60]


**2D array Slicing**

arr[row_slice, column_slice]

In [25]:
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [26]:
print(arr2[0:2, 0:2])

[[10 20]
 [40 50]]


In [27]:
print(arr2[:,1])    # 1st colo

[20 50 80]


In [29]:
print(arr2[0,:])  # 0th row
print(arr2[1,:])  #1st row

[10 20 30]
[40 50 60]


In [34]:
print(arr2[1:,])

print()
print(arr2[2:,])

[[40 50 60]
 [70 80 90]]

[[70 80 90]]


**Changing Element**

**We can modify NumPy array elements by assigning a new value using their index or slice.**

In [53]:
# 1D Array

narr = np.array([10,20,30,40,50])
print(narr)
print("Element at index 3 = ",narr[3])
print()
narr[3] = 45
print("Element at index 3 After change = ", narr[3])
print(narr)

# Multiple Elements using scling  1:3 -> 101
print()
narr[1:4] = 101
print(narr)

[10 20 30 40 50]
Element at index 3 =  40

Element at index 3 After change =  45
[10 20 30 45 50]

[ 10 101 101 101  50]


In [50]:
# 2D Array
narr2 = np.array([
    [10,20,30],
    [40,50,60]
])
print(narr2)

print()
narr2[1,2] = 100

print(narr2)


[[10 20 30]
 [40 50 60]]

[[ 10  20  30]
 [ 40  50 100]]


**Reshape()**

**reshape() changes the dimensions or shape of an array without changing its elements.**

In [63]:
ar = np.array([10,20,30,40,50,60,70,80,90])

new_arr = ar.reshape(3,3)  # 3 row , 3 col
print(new_arr)

print()

ne_ar = ar.reshape(1,9)  # 1 row , 9  col
print(ne_ar)

print()

ne_ar1 = ar.reshape(9,1)  # 9 row, 1 col
print(ne_ar1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 30 40 50 60 70 80 90]]

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


**Flatten()**

**flatten() convert a 2D/ 3D array into 1D array**

**flatten() converts a multidimensional array into a 1D array and returns a copy**

In [79]:
# 2D Array
arrf = np.array([
    [10,20,30],
    [40,50,60]
])
# 2D -> 1D
new_arr = arrf.flatten()  # convert it into 1d array
print(new_arr)

new_arr[0] = 101  #  not
print("\nFlatten Change or not\n")
print(new_arr)

print()
print(arrf)  # original array will not be change after change in new_aray

[10 20 30 40 50 60]

Flatten Change or not

[101  20  30  40  50  60]

[[10 20 30]
 [40 50 60]]


In [71]:
# 3D array
arrf1 = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])

print(arrf1.shape)  # shape - size of each dimension

new_arr = arrf1.flatten()
print(new_arr)

(2, 2, 2)
[10 20 30 40 50 60 70 80]


**Ravel()**

**ravel() also convert multidimensional array into 1D**

In [82]:
arr_r = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr_r)
print()

new_arr = arr_r.ravel()
print(new_arr)

new_arr[0] = 101
print("\n new_array After Modifying\n")
print(new_arr)


print("\nOriginal Array\n")
print(arr_r)   # original Array also modify after chage in new_arr
print()

[[10 20 30]
 [40 50 60]]

[10 20 30 40 50 60]

 new_array After Modifying

[101  20  30  40  50  60]

Original Array

[[101  20  30]
 [ 40  50  60]]



**flatten() vs ravel()**

**faltten() -**
1. return copy.
2. after change in new_arr the original array will not be affected.
3. use more memory.
4. sightly less memory- efficient.



**ravel() -**
1. Returns view when possible.
2. after change in new_arr the original array will also change.
3. uses less memory.
4. more memory efficient.

**Array Iteration**

**Array iteration means accessing each element of an array one by one using a loop.**

In [85]:
# 1D array
arr = np.array([10,20,30,40])

for x in arr:
  print(x, end=" ")

10 20 30 40 

In [88]:
# 2D array
arr = np.array([
    [10,20],
    [30,40]
])

for row in arr:
  print(row)
  print()

[10 20]

[30 40]

