**Day 3 - Array Operation**

1. Arithmetic Operations
2. Mathematical Functions
3. Scaler Operations
4. Element-wise Operations (similar to arthmetic)
5. Comparison Operations
6. Universal Function
7. Aggregation with Arithmetic


**What arithmetic operations does NumPy support?**

**NumPy supports element-wise arithmetic operations such as addition, subtraction, multiplication, division, modulus, and power.**

In [3]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])

In [7]:
print(a + b) # [12 24 35]
print(a - b) # [8 16 25]
print(a * b) # [20 40 150]
print(a / b)   # [5. 5. 6.]
print(a % b)   # [0 0 0]
print(a ** b)  # [100 160000 24300000]

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]
[0 0 0]
[     100   160000 24300000]


**Mathematical Functions**

**NumPy provides mathematical functions such as sqrt(), abs(), round(), floor(), and ceil() for performing calculations on array elements.**

In [20]:
c = np.array([10.4, 20.6, 30.7, 40.2])

d = np.array([-1.8,-67.8])


print("Sqrt: ",np.sqrt(c))  # square root

print("\nUsing abs: ",np.abs(d))   # absolute value- make all positive value

print(np.round(c)) # round

print("Floor: ",np.floor(c)) # round down
print("Round Up: ",np.ceil(c))  # round up

Sqrt:  [3.2249031  4.53872229 5.54075807 6.34034699]

Using abs:  [ 1.8 67.8]
[10. 21. 31. 40.]
Floor:  [10. 20. 30. 40.]
Round Up:  [11. 21. 31. 41.]


**Scaler Operation**

**A scalar operation is an operation performed between a NumPy array and a single value, applied element-wise to all elements.**

In [27]:
arr = np.array([10,20,30,40])

print(arr)

print("Adding 5: ", arr + 5)
print("Sub 2: ", arr -2)
print("Mul 6: ", arr * 6)
print("Div 10: ", arr / 10)


[10 20 30 40]
Adding 5:  [15 25 35 45]
Sub 2:  [ 8 18 28 38]
Mul 6:  [ 60 120 180 240]
Div 10:  [1. 2. 3. 4.]


**Comparison Opeartion**

**Comparison operations compare array elements and return a Boolean array containing True or False for each element.**

1. greater than >
2. less than <
3. greater than or equal >=
4. less than or equal <=
5. equal to ==
6. not equal to !=

In [34]:
arr = np.array([10,20,30,40,50])

print(arr > 20) # 30 40 50
print(arr < 30) # 10 20
print(arr == 20) # 20
print(arr != 20) # 10   30 40 50
print(arr >= 20)
print(arr <= 10) # 10


[False False  True  True  True]
[ True  True False False False]
[False  True False False False]
[ True False  True  True  True]
[False  True  True  True  True]
[ True False False False False]


**Univarsal Function**

**A ufunc, or Universal Function, is a NumPy function that performs operations element by element on array**

In [41]:
arr = np.array([1, 4, 9, 16])
arr1 = np.array([-2,-5,4])

In [50]:
print(np.sqrt(arr))   # absolute value
print(np.abs(arr1))   # square root
print(np.exp(arr))    # exponentail
print(np.log(arr))    # logarithm
print(np.sin(arr))    # sine
print(np.cos(arr))  # cosine

[1. 2. 3. 4.]
[2 5 4]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


**Aggregation Operations**

**Aggregation means combining all array elements to get one result.**

In [51]:
arr = np.array([10,20,30,40])

In [54]:
print(np.sum(arr))  # sum of element in arr
print(np.prod(arr)) # product of all element in array
print(np.min(arr))  # min elem
print(np.max(arr))  # max ele
print(np.mean(arr)) # average
print(np.median(arr)) # median
print(np.std(arr)) # standard deviation
print(np.var(arr))        # variance

100
240000
10
40
25.0
25.0
11.180339887498949
125.0
