**Day - 4 Statistics & Axis**
1. np.sum() - total/sum
2. np.min() - minimum value
3. np.max() - maximum value
4. np.mean() - average
5. np.median() - median
6. np.std() - standard deviation
7. np.var() - variance
8. np.argmin() - index of minimum
9. np.argmax() - index of maximum
10. Axis concept
11. axis=0 - column-wise
12. axis=1 - row-wise
13. Statistics with axis


**What is np.sum() used for?**

**np.sum() is used to calculate the sum of all elements in a NumPy array.**

In [3]:
# 1. np.sum()
import numpy as np

In [4]:
# 1D
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

# 2D
arr1 = np.array([
    [10,20],
    [5,99]
])

print(np.sum(arr1))


150
134


**What is np.min() used for?**

**np.min() is used to find the minimum value in a NumPy array.**

In [5]:
print("Min Element 1D: ",np.min(arr))
print("Min Element 2D: ", np.min(arr1))


Min Element 1D:  10
Min Element 2D:  5


**What is np.max() used for?**

**np.max() is used to find the maximum value in a NumPy array.**

In [6]:
print("Max Element 1D: ", np.max(arr))
print("Max Element 2D: ", np.max(arr1))

Max Element 1D:  50
Max Element 2D:  99


**What is np.mean() used for?**

**np.mean() is used to calculate the average value of elements in a NumPy array.**

In [7]:
print("Mean from 1D: ",np.mean(arr))
print("Mean from 2D: ",np.mean(arr1))

Mean from 1D:  30.0
Mean from 2D:  33.5


**What is np.median() used for?**

**np.median() is used to find the middle value of an array after sorting its elements.**

In [8]:
print("Median Element 1D: ",np.median(arr))  # internally sort but dont change the orignal array
print("Median Element 2D: ",np.median(arr1)) # internally sort but dont change the orignal array

Median Element 1D:  30.0
Median Element 2D:  15.0


**What is np.std() used for?**

**np.std() is used to measure how much the values in a NumPy array are spread out from their mean.**

In [9]:
arr_s = np.array([10,20,30,40,50,60])
print(np.std(arr_s))

17.07825127659933


In [10]:
# Small std - values are close to the mean
# Large std - values are more spread out
a = np.array([20, 21, 19, 20, 20])
b = np.array([5, 20, 35, 50, 65])

print(np.std(a))
print(np.std(b))

0.6324555320336759
21.213203435596427


**what is np.var() used for?**

**np.var() is used to find how much the values are spread out from the average.**

In [11]:
# 1D
array = np.array([10,20,30,40,50])

print("Variance: ", np.var(array))

# Relationship with std
# 1. variance = std²
# 2. std      = √variance

Variance:  200.0


In [12]:
# 2D
array2d = np.array([
    [10,20,30],
    [40,50,60]
])

print("2D variance: ", np.var(array2d))

2D variance:  291.6666666666667


**np.argmin() ?**

**np.argmin() is used to find the index of the smallest value in an array.**

In [13]:
arr = np.array([232, 101, 450, 78, 320])
print("Min Value Index: ", np.argmin(arr)) # index = 3 , element = 78

Min Value Index:  3


**np.argax() ?**

**np.argmax() is used to find the index of the largest value in an array**

In [14]:
print("Max Value index: ", np.argmax(arr)) #element = 450

Max Value index:  2


In [15]:
arr = np.array([
    [12, 85, 34],
    [67, 23, 91]
])

print(np.argmax(arr))  # element = 95

5


**Axis in numpy**

**Axis tells NumPy which direction to perform an operation.**

In [16]:
arr = np.array([10, 20, 30])

print(np.sum(arr, axis=0))

60


In [21]:
arr2dim = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# axis=0 - uper se neeche, yani col pr operation
# 10  20  30
# ↓   ↓   ↓
# 40  50  60
# 50  70  90   # output
print("axis=0 COl pr operation: ",np.sum(arr2dim, axis = 0))   # axis =0


# Left se right, yani rows par operation.
print("axis=1 Row pr operation: ",np.sum(arr2dim, axis=1))

# 10 -> 20 -> 30  = 60
# 40 -> 50 -> 60  = 150

print()
print("axis=0 - coloums pr operation")
print("axis=1 - rows pr operation")


axis=0 COl pr operation:  [50 70 90]
axis=1 Row pr operation:  [ 60 150]

axis=0 - coloums pr operation
axis=1 - rows pr operation


**Statistics with axis**

**Now we can use axis with statistical functions like sum, mean, min, max, std, and var.**

In [22]:
# 1. np.sum() - Finds the total of all elements

arr = np.array([10, 20, 30, 40])

print(np.sum(arr)) # Output: 100


# 2. np.min() - Finds the smallest value
arr = np.array([232, 101, 450, 78, 320])
print(np.min(arr)) # Output: 78


# 3. np.max() - Finds the largest value
print(np.max(arr)) # Output: 450


# 4. np.mean() - Finds the average value
arr = np.array([10, 20, 30, 40])

print(np.mean(arr)) # Output: 25.0


# 5. np.median() - Finds the middle value

arr = np.array([50, 10, 30, 40, 20])

print(np.median(arr)) # Output: 30.0


# 6. np.std() - Finds how much values are spread out from the average

arr = np.array([10, 20, 30, 40, 50])

print(np.std(arr))


# 7. np.var() - Finds how much values are spread out from the average

arr = np.array([10, 20, 30, 40, 50])

print(np.var(arr)) # Output: 200.0


# 8. np.argmin() - Returns the index of the smallest value

arr = np.array([232, 101, 450, 78, 320])

print(np.argmin(arr)) # Output: 3


# 9. np.argmax() - Returns the index of the largest value

print(np.argmax(arr)) # Output: 2





# ==============================
# AXIS IN NUMPY
# ==============================

# Axis tells NumPy in which direction
# to perform an operation.


arr = np.array([
    [232, 101, 450],
    [78, 320, 190]
])


# axis=0 - column-wise
# axis=1 - row-wise


# SUM

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))


# MIN

print(np.min(arr, axis=0))
print(np.min(arr, axis=1))


# MAX

print(np.max(arr, axis=0))
print(np.max(arr, axis=1))


# MEAN

print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))


# MEDIAN

print(np.median(arr, axis=0))
print(np.median(arr, axis=1))


# STD

print(np.std(arr, axis=0))
print(np.std(arr, axis=1))


# VAR

print(np.var(arr, axis=0))
print(np.var(arr, axis=1))


# ARGMIN

print(np.argmin(arr, axis=0))
print(np.argmin(arr, axis=1))


# ARGMAX

print(np.argmax(arr, axis=0))
print(np.argmax(arr, axis=1))


# ==============================
# IMPORTANT
# ==============================

# axis=0 - column-wise
# axis=1 - row-wise

# Statistical Functions:
# np.sum()
# np.min()
# np.max()
# np.mean()
# np.median()
# np.std()
# np.var()
# np.argmin()
# np.argmax()

100
78
450
25.0
30.0
14.142135623730951
200.0
3
2
[310 421 640]
[783 588]
[ 78 101 190]
[101  78]
[232 320 450]
[450 320]
[155.  210.5 320. ]
[261. 196.]
[155.  210.5 320. ]
[232. 190.]
[ 77.  109.5 130. ]
[143.94674941  98.88714106]
[ 5929.   11990.25 16900.  ]
[20720.66666667  9778.66666667]
[1 0 1]
[1 0]
[0 1 0]
[2 1]
