**Day 5 - Boolean Indexing &Filtering**
1. comparison opeartors
2. Boolean Array
3. Boolean index
4. Filtering Arrays
5. np.where()
6. Multiple conditions
7. np.logical_and()
8. np.logical_or()
9. np.logical_not
10. 2D array Filtering


In [1]:
import numpy as np

**Comparison Operators**

**Comparison operators are used to compare array values and return True or False.**

In [3]:
arr = np.array([232, 101, 450, 78, 320])

print(arr > 200)
print(arr < 200)
print(arr >= 200)
print(arr <= 200)
print(arr == 200)
print(arr != 200)

[ True False  True False  True]
[False  True False  True False]
[ True False  True False  True]
[False  True False  True False]
[False False False False False]
[ True  True  True  True  True]


**Boolean Array**

**Is Array that Contains only True or False**

In [4]:
res = arr > 200
print(res)

[ True False  True False  True]


**Boolean Indexing**

**Using True or False Conditions to Select vallues from an Array**

In [5]:
print(arr[arr > 200])

[232 450 320]


**Filtering Array**

**Filtering is selecting only the elements that satisfy a given condition.**

In [12]:
arr1 = np.array([145, 67, 320, 89,210])
filter = arr1[arr1 > 100]
print("Print Values which Satisfiy Cond: ",filter) # 67 and 89 are smaller so thas why not print

Print Values which Satisfiy Cond:  [145 320 210]


**np.Where()**

**np.where() is used to find the index/position where a condition is true.**

In [14]:
print(np.where(arr1 > 100))  # 145 320 120

(array([0, 2, 4]),)


**Multiple Conditions**

**Multiple conditions are used when we need to check two or more conditions on an array.(With NumPy, use & and |, not Python's and and or.)**

In [19]:
new_arr = np.array([80,150,250,350,200])

result = new_arr[(new_arr > 100) & (new_arr < 300)]
print(result)

print(new_arr[(new_arr < 100) | (new_arr > 300)])

print(new_arr[~(new_arr > 100)])   # only 80 is less than 100

[150 250 200]
[450  78 320]
[80]


**np.logical_and()**

**np.logical_and() is used when both conditions must be True.**

In [21]:
ans = np.logical_and((new_arr > 100), new_arr < 300)
print(ans)

[False  True  True False  True]


**np.logical_or()**

**Is used when at least one condition should be true.**

In [26]:
result = np.logical_or(new_arr < 100, new_arr > 300)
print(result)
print(new_arr[result])

[ True False False  True False]
[ 80 350]


**np.logical_not()**

**Is used to reverse a condition**
True -> False
False -> True

In [28]:
res_not = np.logical_not(new_arr > 200)
print(res_not)
print(new_arr[res_not])

[ True  True False False  True]
[ 80 150 200]


**2D Array Filtering**

**2D array filtering selects elements from a 2D array based on a condition.**

In [29]:
arr = np.array([
    [120, 45, 300],
    [80, 250, 60]
])

# It checks every element and keeps only values greater than 100.
result = arr[arr > 100]

print(result)

[120 300 250]
