**Day 6 - Joining &_ Spliting Arrays**
1. np.concatenate()
2. np.stack()
3. np.vstack()
4. np.hstack()
5. np.dstack()
6. np.split()
7. np.array_split()
8. np.vsplit()
9. np.hsplit()

Joining - combining Multiple arrays into one.

spliting - breaking one array into multiple.

**np.concatenate()**

**Is used to join two or more arrays together.**

**Statistics mein:**

1. axis=0 column-wise,

2. axis=1 row-wise.



**Concatenate mein:**

 1. axis=0 rows join,

 2. axis=1 columns join.

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

In [2]:
res = np.concatenate((arr1, arr2))  # join two separate arr into one arr
print(res)

[10 20 30 40 50 60]


In [4]:
arr2d1 = np.array([
    [10, 20],
    [30, 40]
])

arr2d2 = np.array([
    [50, 60],
    [70, 80]
])                             # axis = 0 row wise
                               # axis = 1 col wise

In [5]:
np.concatenate((arr2d1, arr2d2))
# by deafult assus ekrta hai ki 0 so row wise

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [6]:
np.concatenate((arr2d1,arr2d2), axis = 0) # 0 -> row wise

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [7]:
np.concatenate((arr2d1,arr2d2), axis = 1) # 1 -> col wise

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

**np.stack()**

**np.stack() joins two or more arrays and creates a new axis.**

In [13]:
print("arr1: ",arr1)
print("arr2: ",arr2)

print()

print("using Stack- it join arr1 & arr2 in 2D arr")
ans1 = np.stack((arr1,arr2))
print(ans1)  #

arr1:  [10 20 30]
arr2:  [40 50 60]

using Stack- it join arr1 & arr2 in 2D arr
[[10 20 30]
 [40 50 60]]


**np.vstack() - vertical stack**

**np.vstack() joins arrays vertically, one below another.**

In [15]:
arr3 = np.array([70,80,90])

res = np.vstack((arr1,arr2,arr3))
print(res)

# So all three arrays are joined vertically, one below another.

[[10 20 30]
 [40 50 60]
 [70 80 90]]


**np.hstack() - horizaontal stack**

**np.hstack() joins arrays horizontally, side by side.**


In [17]:
resh = np.hstack((arr1,arr2,arr3))
print(resh)

[10 20 30 40 50 60 70 80 90]


Diffrenece bwn vstack() vs hstack()

vstack() - one below another

hstack() - side by side

**# np.dstack()**

joins along 3rd axis

In [18]:
array1 = np.array([
    [10, 20],
    [30, 40]
])

array2 = np.array([
    [50, 60],
    [70, 80]
])

result = np.dstack((array1, array2))

print(result)   # Here, the two 2D arrays are combined to create a 3D array.


[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]


**# np.split()**

**Is used to divide one array into multiple smaler arrays.**

[10, 20, 30, 40, 50, 60]

           ↓

[10, 20]  [30, 40]  [50, 60]

In [29]:
split_arr = np.array([10,20,30,40,50,60])

ans2 = np.split(split_arr,3)  # 3 equal part

for i in ans2:
  print("Array: ",i)

print()

ans3 = np.split(split_arr,2)   # 2 equal part
for i in ans3:
  print("Array: ",i)

Array:  [10 20]
Array:  [30 40]
Array:  [50 60]

Array:  [10 20 30]
Array:  [40 50 60]


**np.array_split()**

**np.array_split() is similar to np.split(), but it can split an array into unequal parts.**

In [35]:
unsplit = np.array([10,20,30,40,50])  # it Split UNEqual Part

un1 = np.array_split(unsplit,3)
print(un1)

print()

un2 = np.array_split(unsplit,4)
print(un2)

[array([10, 20]), array([30, 40]), array([50])]

[array([10, 20]), array([30]), array([40]), array([50])]


**np.vsplit()**

**Is used to split 2D array vertically, meaning it splits the array by rows**

In [40]:
arr_1 = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80]
])

result = np.vsplit(arr_1,2)

for i in result:
  print(i)
  print()

# vsplit() - split rows
# hsplit() - split columns

[[10 20]
 [30 40]]

[[50 60]
 [70 80]]



**np.hsplit()**

**np.hsplit() is used to split a 2D array horizontally, meaning it splits the array by columns.**

In [42]:
result_col = np.hsplit(arr_1, 2)

for i in result_col:
  print(i)
  print()

[[10]
 [30]
 [50]
 [70]]

[[20]
 [40]
 [60]
 [80]]

