**Day 7 - Sorting & Searching**

1. np.sort() - sort array values
2. np.argsort() - get indexes of sorted values
3. np.searchsorted() - find insertion position
4. np.where() - find positions based on a condition
5. np.unique() - get unique values
6. np.count_nonzero() - count non-zero values
7. Finding indexes using conditions
8. Filtering + Sorting

**1. np.Sort()**

**Is used to Sort the elements of an array.**

In [1]:
import numpy as np

In [3]:
arr1 = np.array([45, 12, 89, 23, 67])

res1 = np.sort(arr1)  # by defaukt sort asc order
print(res1)

[12 23 45 67 89]


In [22]:
arr_2d = np.array([
    [45, 12, 89],
    [67, 23, 10]
])

print(np.sort(arr_2d))   # by default sort asc by each row
print()
print(np.sort(arr_2d, axis = 1))  # axis = 1 sort each row

[[12 45 89]
 [10 23 67]]

[[12 45 89]
 [10 23 67]]


**2. np.argsort()**

**np.argsort() returns the indexes that would sort the array.**

**sort() vs argsort()**

**1. np.sort()** - gives sorted values

**2. np.argsort()** - gives indexes of sorted values

In [21]:
print(np.argsort(arr1))  # print the sorted values index

[1 3 0 4 2]


**3. np.searchsorted()**

**np.searchsorted() finds the position where a value should be inserted to keep the array sorted.**

In [20]:
arr2 = np.array([10,20,30,40,50])

# it find the position where it should be inserted.
print("Insert At Position: ",np.searchsorted(arr2, 35))

print("Insert At: ", np.searchsorted(arr2,25))

Insert At Position:  3
Insert At:  2


**4. np.where()**

***We already used np.where(),but it is also useful for searching because it can find the indexes where a condition is True.***

In [19]:
arr = np.array([45, 12, 89, 23, 67])

result = np.where(arr > 40)

print(result)

# 45 - index 0
# 89 - index 2
# 67 - index 4

(array([0, 2, 4]),)


**5. Unique()**

**is used to get unique values, meaning duplicate values are removed.**

In [18]:
arr3 = np.array([10,20,10,30,20,40,30])

res3 = np.unique(arr3)  # remove dup & keep only unique
print(res3)

[10 20 30 40]


In [17]:
arr4 = np.array([50, 20, 40, 20, 10, 50])

print(np.unique(arr4))   # it remove dup & also sort the ac to values.

[10 20 40 50]


**6. np.count_nonzero()**

**It Counts how many elements are not in the array.**

In [25]:
arr4 = np.array([10,0,30,20,0,40,15])

print("Count NonZero Element: ",np.count_nonzero(arr4))
print("Count Element > 20: ",np.count_nonzero(arr4 > 20))

Count NonZero Element:  5
Count Element > 20:  2


**7. Finding Index & using Condition**

**np.where() returns the indexes where a given condition is True.**

In [27]:
arr5 = np.array([15,42,8,67,23])

indexes = np.where(arr5 > 20)
print("At Position: ",indexes)

At Position:  (array([1, 3, 4]),)


**8. Filtering & Sorting**

**Filtering** - select values based on a condition

**Sorting** - arrange those selected values

In [30]:
arr6 = np.array([45, 12, 78, 23, 56, 9])

result6 = arr6[arr6 > 20]

print("Filtering: ",result6)   # [45 78 23 56]

print("Sorting After Filter: ",np.sort(result6))

Filtering:  [45 78 23 56]
Sorting After Filter:  [23 45 56 78]
