**Day 8 - BroadCasting**

**BroadCasting is a NumPy Feature that allows NumPy to Performs Opeartions on arrays with a different shapes when their shapes are compatible.**

1. Broadcasting Concept
2. Scalar Broadcasting
3. Array Broadcasting
4. Broadcasting Rules
5. Shape Compatibility
6. 2D Broadcasting
7. Broadcasting Errors
8. Practical Broadcasting

**1. Broadcasting Concept**

In [2]:
import numpy as np

In [5]:
arr = np.array([10,20,30])

# 5 is Added to every elemnet
print(arr + 5)

# Broadcasting = NumPy automatically adjusts smaller values/arrays
# to perform operations with larger arrays.

[15 25 35]


Rule- For broadcasting to work, the array shapes must be compatible.

In [8]:
a = np.array([10, 20, 30]) # size = 3
b = np.array([1, 2, 3])    # size = 3

print(a + b) # both array have same shape so broadcasting Work.

[11 22 33]


In [9]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2, 3])

print(a + b)

[[11 22 33]
 [41 52 63]]


**2. Scalar BroadCasting**

**Scalar broadcasting means applying a single value to every element of an array during an operation.**

In [12]:
s1 = np.array([10,20,30,40])
print(s1 * 5)
print(s1 + 2)
print(s1 - 2)
print(s1 /10)

[ 50 100 150 200]
[12 22 32 42]
[ 8 18 28 38]
[1. 2. 3. 4.]


**3. Array Broadcasting**

**Array Broadcasting: Performing operations between arrays of different shapes when their shapes are compatible.**

In [13]:
a = np.array([10, 20, 30])
b = np.array([1])

print(a + b)

[11 21 31]


In [14]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


**4. Broadcasting Rules**

**Determine whether different-shaped arrays can perform operations together.**

**Main rules**
1. Dimensions are equal - works
2. One dimension is 1 - works
3. Missing dimensions are treated as 1
4. Otherwise - Broadcasting Error

**Rule 1:** If corresponding dimensions of two arrays are equal, broadcasting works.

In [16]:
# For Rule 1: Same dimension = Compatible ✅
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


**Rule 2: If one corresponding dimension is 1, broadcasting works.**

In [17]:
# for Rule 2: Dimension 1 = Compatible ✅
a = np.array([10, 20, 30])
b = np.array([5])

print(a + b)

[15 25 35]


**Rule 3:** If one array has fewer dimensions, NumPy treats the missing dimensions as 1.

In [19]:
# for Rule 3: Missing dimension are Treated as 1
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2, 3])

print(a + b)

# a - (2, 3)  shape of a
# b - (3,)    shape of b

[[11 22 33]
 [41 52 63]]


**Rule 4:** If the dimensions are not equal and neither dimension is 1, broadcasting does not work.

In [21]:
# Rule 4: Incompatible Dimension
a = np.array([10, 20, 30, 40])
b = np.array([1, 2])

print(a + b) # then here brodcasting not work and show Error

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

**5.Shape Compatibility**

**Two arrays are shape-compatible when their dimensions are equal or one of them is 1.**

Equal or 1 = Compatible ✅

Different and neither is 1 = Not Compatible ❌

**6. 2D BroadCasting**

**A smaller array is automatically expanded to match a 2D array when the shapes are compatible.**

In [23]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2, 3])

print(a + b)  # b is broadcast across each row.

[[11 22 33]
 [41 52 63]]


**7. Broadcasting Errors**

**A broadcasting error occurs when two arrays have incompatible shapes.**

In [24]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2])

print(a + b)   # Incompatible shapes = Broadcasting Error ❌

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**8. Practical Broadcasting**

ex: real life example , add marks to every student

In [27]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

bonus = np.array([5, 5, 5])

result = marks + bonus

print(result)   # bonus is automatically applied to each row.

[[75 85 95]
 [65 80 90]]
