**Day 9 - Copy & View**
1. Copy
2. View
3. Difference between Copy and View
4. base attribute
5. Memory Sharing

**1. Copy**

**copy creates completely independent array with separate data.**

In [1]:
import numpy as np

In [9]:
a = np.array([10,20,30])

b = a.copy()

print("Original a: ", a)

print("copy array b: ",b)
b[0] = 99
print("After Change copy b: ",b)

# b has its own separate data, so changing b does not affect a.

Original a:  [10 20 30]
copy array b:  [10 20 30]
After Change copy b:  [99 20 30]


**2. View**

**View creates a new array that shares the same data as the original array.**

In [12]:
arr1 = np.array([10,20,30])

arr_b = arr1.view()

arr_b[0] = 100

print("Original: ", arr1)
print("View: ", arr_b)

# View = Same data, different array.

Original:  [100  20  30]
View:  [100  20  30]


| Copy                          | View                        |
| ----------------------------- | --------------------------- |
| Creates separate data         | Shares original data        |
| Changes don't affect original | Changes can affect original |
| Uses more memory              | Uses less memory            |
| `a.copy()`                    | `a.view()`                  |


**3. Difference Between Copy and View**


In [17]:
x = np.array([10,20,30])

copy_arr = x.copy()
view_arr = x.view()

print("Just Printing\n")
print("X: ", x)
print("Copy Arr: ",copy_arr)
print("View Arr: ",view_arr)

copy_arr[0] = 101
view_arr[0] = 999

print("\n After Change Print\n")

print("x: ", x)             # original are affted by view_arr 999
print("Copy Arr: ",copy_arr)
print("View Arr: ",view_arr)

Just Printing

X:  [10 20 30]
Copy Arr:  [10 20 30]
View Arr:  [10 20 30]

 After Change Print

x:  [999  20  30]
Copy Arr:  [101  20  30]
View Arr:  [999  20  30]


**Why?**

**1. copy_arr** has separate data, so changing it doesn't affect x array.

**2. view_arr** shares data with x array, so changing it affects x array.


**Copy = Separate data**
**View = Shared data**

**4. Base**

**base tells you whether an array shares data with another array.**

In [19]:
# Copy = No shared data
# View = Shared data

z = np.array([10,20,30])

m = z.view()
n = z.copy()

print(m.base)
print(n.base) # show none bcz copy has seperate data,  No shared data.

[10 20 30]
None


**5. Memory Sharing**

**Memory sharing means two arrays use the same underlying data in memory.**

In [23]:
a = np.array([10,20,30])

b = a.view()

b[0] = 999

print(a)
print(b)

# memory sharing checking wheater two array actually shared the smae memory.
print(np.shares_memory(a,b))

c = a.copy()  # copy does not shared memory

print(np.shares_memory(a,c))  # False

# Here a and b share the same memory/data.

[999  20  30]
[999  20  30]
True
False
