**Day 10 - Random Module**

1. np.random
2. rand()
3. randint()
4. randn()
5. random()
6. choice()
7. shuffle()
8. permutation()
9. seed()

**1. Random - np.random()**

**np.random is NumPy's module for generating random numbers and random data.**

In [6]:
import numpy as np

In [7]:
print(np.random.rand())

0.0722560422899382


In [11]:
print(np.random.randint(1,10))

9


**2. rand()**

np.random.rand() generates random numbers between 0 and 1.

In [12]:
# one number
print(np.random.rand())

0.7969002149822974


In [13]:
# Multiple Random Numbers
print(np.random.rand(5))

[0.34271479 0.74864402 0.34154435 0.25721961 0.96694953]


In [14]:
# 2D array
print(np.random.rand(2,3))   # 2 row , 3 col

[[0.49756822 0.71860987 0.70191058]
 [0.0689829  0.1274528  0.77014419]]


**3. randint()**

randint() generates random integers within a specified range.

In [15]:
# One Number
print(np.random.randint(1,10))

9


In [16]:
# Generate 5 Number
print(np.random.randint(1,10,5))

[9 2 9 1 6]


In [19]:
# 2D array
print(np.random.randint(1,100, size=(2,3)))

[[ 8 47 20]
 [34  2 97]]


**4. randn()**

**np.random.randn() generates random numbers based on a standard normal distribution.**


In [23]:
print(np.random.randn(5))  # it can create positive and negative values

[-0.38297812 -2.84909288  0.8013314  -0.4394187   0.46340536]


In [24]:
print(np.random.randn(2,3))

[[-2.13662746 -0.08816124  0.70358688]
 [-2.53007337 -1.10435666  1.93261754]]


| `rand()`                             | `randn()`                          |
| ------------------------------------ | ---------------------------------- |
| Generates values between **0 and 1** | Generates values around **0**      |
| Uniform distribution                 | Standard normal distribution       |
| Values are always positive           | Values can be positive or negative |
| Example: `0.2, 0.7, 0.4`             | Example: `-1.2, 0.5, 1.3`          |


**5. random()**

**random() generates random floating-point numbers between 0 and 1**

In [27]:
# One Number
print(np.random.random())

0.7628503998688722


In [33]:
# Multiple
print(np.random.random(4))

[0.56371996 0.35488738 0.21378177 0.60816372]


In [35]:
# 2D array
print(np.random.random((2, 3)))

[[0.66963727 0.305031   0.78035148]
 [0.36866966 0.72320063 0.61358973]]


**6. Choice()**

np.random.choice() is used to randomly select values from an array.

In [40]:
arr = np.array([10,20,30,40,50])

print(np.random.choice(arr))
# Each time we run it select diffrenet value

10


**7. shuffle()**

**np.random.shuffle() is used to randomly rearrange the elements of an array.**

In [54]:
arr= np.array([10,20,30,40,50])

np.random.shuffle(arr)

print(arr)   # randomly reagrrange the original array

[20 50 10 40 30]


In [45]:
r = np.random.shuffle(arr)
print(r)

# Why ? none
# shuffle change the original array directly and return None

None


**8.Permutation()**

**np.random.permutation() is used to randomly rearrange an array and return a new array.**

In [71]:
array = np.array([10,20,30,40,50])

r = np.random.permutation(array)

print("Original: ", array)  # original not change

# permutation- does not change the original array, Return new shuffled array.
print("Permutation: ", r)

Original:  [10 20 30 40 50]
Permutation:  [20 50 40 10 30]


**1. shuffle**

**np.random.shuffle(arr)**


*   Change Original array
*   Return None



**2. permutataion()**

**r = np.random.permutation(arr)**



*   Does not change the original array
*   Return new shuffled array



**9. seed()**

**np.random.seed() is used to get the same random results every time.**

Without Seed()

In [75]:
print(np.random.randint(1,10,5))

[2 5 1 3 2]


with seed()

In [80]:
np.random.seed(10)

print(np.random.randint(1,10,5))

# Every time you run this code, we get the same sequence of random numbers.

[5 1 2 1 2]
